### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tlworks** [mistzzt/RegionTrigger#4]
https://i.gyazo.com/b54ef0848b682fd78620685232f2d81c.png

**Comment by mistzzt** [comment]
It seemed that nobody left the server but OnServerLeave was called. 
Please tell me version of your current rt plugin

**Comment by tlworks** [comment]
Using the latest available on Github, I downloaded it and build it using the latest TShock release. But it would probably occur on the latest release as well.

Additional note;
Please change the command usage, it's confusing and I don't really know how to use the command properly. I suggest going with something like: /rt add <region> <flag> <additional parameters>.

**Comment by mistzzt** [comment]
I have updated the release and you can fix this issue right now.
I will give an example telling how to use the command in detail.

By the way, the reason i dont think that '/rt add' is not a good idea is it can make parameters too long.
/rt set-event main-region message -- /rt add event main-region message

**Can you suggest me a better way to change the command, which makes sure that parameters will not be too long, and not be confusing?**

In fact, i failed and finally chose '/rt set-<property>'.

**Comment by mistzzt** [comment]
Hmm, i dont think that i should change --help to help, as well as --del
